### ISSUE TITLE
Crash when no Terminal.html (Binary release dev-20210927a)

### ISSUE THREAD

**Issue by dggfi** [viktor-ferenczi/EnhancedUI#10] opened 2021-09-27 00:57 UTC
I deleted (renamed) the `Content/Terminal.html` file to see how the game behaves when the page is missing. When the server is turned off, EnhancedUI loads nothing. Duh, this is expected behavior. However, when the server is turned on, the game will imminently crash. Sometimes immediately, and at least once after making multiple requests to `localhost:3000`

![image](https://user-images.githubusercontent.com/91400038/134830808-a9addccd-4889-4f6e-bc0a-01903d13a705.png)

This is not a pertinent issue, but it may be desirable for EnhancedUI to fail silently, or at least provide a dialog explaining the error then restoring the vanilla UI, if possible.

**Comment by viktor-ferenczi** [comment] 2021-09-28 20:58
I could not reproduce the issue. It does not crash and I don't see the above errors in the game's log, nor in the browser component's `debug.log` which is next to the game's executable. Where did you find those log lines?

The game detects whether the `Content` directory exists once on plugin load (startup), then it does not check this anymore. It sticks with the decision made on startup whether it loads the local files or connects to the dev server on port 3000. Please see the class `WebContent` in the plugin's C# source code for the detailed logic. This is why I don't understand how a Web server listening or not on `localhost:3000` would cause the game to crash if not used (connected to).

**Comment by WesternGamer** [comment] 2021-11-04 01:18
Issue closed as it is over 30 days old and the issued is in an old binary release (dev-20210927a). The current binary release at the time of writing is dev-20211031b.

**Closed by WesternGamer** 2021-11-04 01:18 UTC
